import { Link, createFileRoute, notFound } from "@tanstack/react-router";
import { ExternalLink, ScrollText } from "lucide-react";
import { ExternalImage } from "../components/ExternalImage.js";
import { GamePosition } from "../components/GamePosition.js";
import { QuestTimeline } from "../components/QuestTimeline.js";
import { NotFoundPanel } from "../components/NotFoundPanel.js";
import { getQuestData } from "../data/staticContentClient.js";
import { routeParamToQuestKey } from "../data/questRoute.js";

export const Route = createFileRoute("/quests/$questKey")({ loader: async ({ params }) => { const value = await getQuestData({ data: { questKey: routeParamToQuestKey(params.questKey) } }); if (!value) throw notFound(); return value; }, component: QuestPage, notFoundComponent: () => <NotFoundPanel message="Cette quête n’existe pas dans le carnet." /> });
function QuestPage() { const { quest, steps } = Route.useLoaderData(); return <div className="mx-auto max-w-4xl space-y-7"><div className="breadcrumbs text-sm"><ul><li><Link to="/quests">Quêtes</Link></li><li>{quest.originalName ?? quest.questKey}</li></ul></div><section className="card border border-base-300 bg-base-100 shadow-md"><div className="card-body"><div className="flex flex-col gap-5 sm:flex-row"><div className="avatar"><div className="mask mask-squircle h-24 w-24 bg-base-200"><ExternalImage src={quest.npcImageUrl} alt={quest.npcName ? `Portrait de ${quest.npcName}` : "Portrait du PNJ"} className="h-full w-full object-cover" /></div></div><div className="flex-1"><div className="flex flex-wrap gap-2">{quest.category && <span className="badge badge-primary">{quest.category}</span>}<span className="badge badge-outline">{quest.questKey}</span></div><h1 className="mt-2 text-3xl font-bold">{quest.originalName ?? quest.questKey}</h1>{quest.npcName && <p className="mt-2 flex items-center gap-2 opacity-70"><ScrollText size={17} />{quest.npcName}</p>}<div className="mt-4"><GamePosition position={{ map: quest.startMap, cmd: quest.travelCommand, x: quest.startX, y: quest.startY }} /></div></div></div>{quest.externalUrl && <div className="card-actions justify-end"><a className="btn btn-primary gap-2" href={quest.externalUrl} target="_blank" rel="noreferrer">Guide externe<ExternalLink size={17} /></a></div>}</div></section><div role="tablist" className="tabs tabs-lift"><input type="radio" name="quest-tabs" role="tab" className="tab" aria-label="Résumé" defaultChecked /><div role="tabpanel" className="tab-content rounded-box border-base-300 bg-base-100 p-6"><p>Cette quête apparaît {steps.length} fois dans le guide local.</p></div><input type="radio" name="quest-tabs" role="tab" className="tab" aria-label="Étapes" /><div role="tabpanel" className="tab-content rounded-box border-base-300 bg-base-100 p-6"><QuestTimeline occurrences={steps} /></div><input type="radio" name="quest-tabs" role="tab" className="tab" aria-label="Données" /><div role="tabpanel" className="tab-content rounded-box border-base-300 bg-base-100 p-6"><div className="collapse collapse-arrow bg-base-200"><input type="checkbox" /><div className="collapse-title font-medium">Valeur normalisée conservée</div><div className="collapse-content"><pre className="overflow-auto text-xs">{JSON.stringify(quest.value, null, 2)}</pre></div></div></div></div></div>; }
