/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesGuideIdRouteImport } from './routes/guides.$guideId'
import { Route as QuestsIndexRouteImport } from './routes/quests.index'
import { Route as QuestsQuestKeyRouteImport } from './routes/quests.$questKey'
import { Route as SharedShareTokenRouteImport } from './routes/shared.$shareToken'
import { Route as GuidesGuideIdStepsStepNumberRouteImport } from './routes/guides.$guideId_.steps.$stepNumber'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdRoute = GuidesGuideIdRouteImport.update({
  id: '/guides/$guideId',
  path: '/guides/$guideId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsIndexRoute = QuestsIndexRouteImport.update({
  id: '/quests/',
  path: '/quests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsQuestKeyRoute = QuestsQuestKeyRouteImport.update({
  id: '/quests/$questKey',
  path: '/quests/$questKey',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedShareTokenRoute = SharedShareTokenRouteImport.update({
  id: '/shared/$shareToken',
  path: '/shared/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesGuideIdStepsStepNumberRoute =
  GuidesGuideIdStepsStepNumberRouteImport.update({
    id: '/guides/$guideId_/steps/$stepNumber',
    path: '/guides/$guideId/steps/$stepNumber',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/progress': typeof ProgressRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/quests/$questKey': typeof QuestsQuestKeyRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/guides/': typeof GuidesIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/guides/$guideId/steps/$stepNumber': typeof GuidesGuideIdStepsStepNumberRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/progress': typeof ProgressRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/quests/$questKey': typeof QuestsQuestKeyRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/guides': typeof GuidesIndexRoute
  '/quests': typeof QuestsIndexRoute
  '/guides/$guideId/steps/$stepNumber': typeof GuidesGuideIdStepsStepNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/design-system': typeof DesignSystemRoute
  '/progress': typeof ProgressRoute
  '/guides/$guideId': typeof GuidesGuideIdRoute
  '/quests/$questKey': typeof QuestsQuestKeyRoute
  '/shared/$shareToken': typeof SharedShareTokenRoute
  '/guides/': typeof GuidesIndexRoute
  '/quests/': typeof QuestsIndexRoute
  '/guides/$guideId_/steps/$stepNumber': typeof GuidesGuideIdStepsStepNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/progress'
    | '/guides/$guideId'
    | '/quests/$questKey'
    | '/shared/$shareToken'
    | '/guides/'
    | '/quests/'
    | '/guides/$guideId/steps/$stepNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/design-system'
    | '/progress'
    | '/guides/$guideId'
    | '/quests/$questKey'
    | '/shared/$shareToken'
    | '/guides'
    | '/quests'
    | '/guides/$guideId/steps/$stepNumber'
  id:
    | '__root__'
    | '/'
    | '/design-system'
    | '/progress'
    | '/guides/$guideId'
    | '/quests/$questKey'
    | '/shared/$shareToken'
    | '/guides/'
    | '/quests/'
    | '/guides/$guideId_/steps/$stepNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignSystemRoute: typeof DesignSystemRoute
  ProgressRoute: typeof ProgressRoute
  GuidesGuideIdRoute: typeof GuidesGuideIdRoute
  QuestsQuestKeyRoute: typeof QuestsQuestKeyRoute
  SharedShareTokenRoute: typeof SharedShareTokenRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
  QuestsIndexRoute: typeof QuestsIndexRoute
  GuidesGuideIdStepsStepNumberRoute: typeof GuidesGuideIdStepsStepNumberRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId': {
      id: '/guides/$guideId'
      path: '/guides/$guideId'
      fullPath: '/guides/$guideId'
      preLoaderRoute: typeof GuidesGuideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/': {
      id: '/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof QuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests/$questKey': {
      id: '/quests/$questKey'
      path: '/quests/$questKey'
      fullPath: '/quests/$questKey'
      preLoaderRoute: typeof QuestsQuestKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$shareToken': {
      id: '/shared/$shareToken'
      path: '/shared/$shareToken'
      fullPath: '/shared/$shareToken'
      preLoaderRoute: typeof SharedShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$guideId_/steps/$stepNumber': {
      id: '/guides/$guideId_/steps/$stepNumber'
      path: '/guides/$guideId/steps/$stepNumber'
      fullPath: '/guides/$guideId/steps/$stepNumber'
      preLoaderRoute: typeof GuidesGuideIdStepsStepNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignSystemRoute: DesignSystemRoute,
  ProgressRoute: ProgressRoute,
  GuidesGuideIdRoute: GuidesGuideIdRoute,
  QuestsQuestKeyRoute: QuestsQuestKeyRoute,
  SharedShareTokenRoute: SharedShareTokenRoute,
  GuidesIndexRoute: GuidesIndexRoute,
  QuestsIndexRoute: QuestsIndexRoute,
  GuidesGuideIdStepsStepNumberRoute: GuidesGuideIdStepsStepNumberRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
